services:
  mongo:
    image: mongo:4.4.18
    container_name: mongo_test
    ports: 
      - 27017:27017  
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_db_user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  incident_reports:
    build: .
    ports:
      - 50005:8080
    depends_on:
      - mongo
    environment:
      - DB_IMPLEMENTATION=MONGODB 
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_USERNAME=mongo_db_user 
      - DB_PASSWORD=password 
    volumes:
      - .:/app

volumes:
  mongo:
