services:
  nginx:
    image: nginx:stable-alpine-slim
    ports:
      - 8089:80
      - 80:80
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf

  accounts:
    build: ../src/accounts
    ports:
      - 50001:8080
      
  permissions:
    build: ../src/permissions
    ports:
      - 50002:8080
      
  sessions:
    build: ../src/sessions
    ports:
      - 50003:8080

  webapp:
    build: ../src/webapp
    ports:
      - 50000:8080

  guest_webapp:
    build: ../src/guest_webapp
    ports:
      - 8081:80
  
  staff_webapp:
    build: ../src/staff_webapp
    ports:
      - 8082:80