include:
  - ../src/guest_webapp/docker-compose.yaml     # uses port 8081
  - ../src/staff_webapp/docker-compose.yaml     # uses port 8082
  - ../src/amenities/docker-compose.yaml        # uses port 50004
  - ../src/task_system/docker-compose.yaml      # uses port 50006
services:
  nginx:
    image: nginx:stable-alpine-slim
    ports:
      - 8089:80
      - 80:80
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf

  accounts:
    build: ../src/accounts
    ports:
      - 50001:8080

  incident_reports: #uses port 50005
    extends:
      file: ../src/incident_reports/docker-compose.yaml
      service: incident_reports
