import { ITask } from '../../models/tasks.model';
import { TaskType, TaskStatus } from '../../models/task-enums';

export const mockTasks: ITask[] = [
  {
    id: 1,
    roomId: 102,
    taskType: TaskType.RoomCleaning,
    description:
      'Guest requested a quick clean of the entire room, including dusting all surfaces, vacuuming the carpets, wiping down mirrors and windows, and changing the bed linens. Additionally, the guest asked for the trash to be emptied and the bathroom to be thoroughly sanitized. They also mentioned needing more toiletries, including shampoo, conditioner, and body lotion.',
    timeCreated: new Date('2024-10-21T08:00:00'),
    assignee: null,
    status: TaskStatus.Pending,
  },
  {
    id: 2,
    roomId: 104,
    taskType: TaskType.Maintenance,
    description: 'Request for additional towels for the room.',
    timeCreated: new Date('2024-10-20T09:30:00'),
    assignee: 'John Doe',
    status: TaskStatus.Completed,
  },
  {
    id: 3,
    roomId: 104,
    taskType: TaskType.FoodDelivery,
    description: 'Dinner requested to be served at 7 PM in the room.',
    timeCreated: new Date('2024-10-21T11:00:00'),
    assignee: 'Jane Smith',
    status: TaskStatus.InProgress,
  },
  {
    id: 4,
    roomId: 106,
    taskType: TaskType.Maintenance,
    description: 'Issue with bathroom faucet leaking since yesterday.',
    timeCreated: new Date('2024-10-20T15:45:00'),
    assignee: null,
    status: TaskStatus.Pending,
  },
  {
    id: 5,
    roomId: 204,
    taskType: TaskType.RoomCleaning,
    description: 'Deep clean requested for the carpets and furniture.',
    timeCreated: new Date('2024-10-21T09:15:00'),
    assignee: 'Sarah Lee',
    status: TaskStatus.InProgress,
  },
  {
    id: 6,
    roomId: 207,
    taskType: TaskType.FoodDelivery,
    description: 'Guest requested a vegan meal to be served in the room.',
    timeCreated: new Date('2024-10-21T10:30:00'),
    assignee: 'Alex K.',
    status: TaskStatus.InProgress,
  },
  {
    id: 7,
    roomId: 207,
    taskType: TaskType.WakeUpCall,
    description: 'Set wake-up call for 7 AM, guest wants to be notified.',
    timeCreated: new Date('2024-10-21T08:30:00'),
    assignee: null,
    status: TaskStatus.Pending,
  },
  {
    id: 8,
    roomId: 303,
    taskType: TaskType.FoodDelivery,
    description: 'Order a bottle of wine and cheese platter.',
    timeCreated: new Date('2024-10-22T14:30:00'),
    assignee: 'Alice W.',
    status: TaskStatus.InProgress,
  },
  {
    id: 9,
    roomId: 305,
    taskType: TaskType.Maintenance,
    description: 'Request for extra pillows.',
    timeCreated: new Date('2024-10-22T10:00:00'),
    assignee: null,
    status: TaskStatus.Pending,
  },
  {
    id: 10,
    roomId: 402,
    taskType: TaskType.LaundryService,
    description: 'Pick up laundry by 9 AM.',
    timeCreated: new Date('2024-10-22T08:30:00'),
    assignee: 'Mark T.',
    status: TaskStatus.Completed,
  },
  {
    id: 11,
    roomId: 408,
    taskType: TaskType.RoomCleaning,
    description: 'Request for a thorough cleaning before guest arrival.',
    timeCreated: new Date('2024-10-21T15:00:00'),
    assignee: 'Mia L.',
    status: TaskStatus.InProgress,
  },
  {
    id: 12,
    roomId: 410,
    taskType: TaskType.Maintenance,
    description: 'Guest requested help with TV setup.',
    timeCreated: new Date('2024-10-21T11:30:00'),
    assignee: 'Tom H.',
    status: TaskStatus.InProgress,
  },
  {
    id: 13,
    roomId: 412,
    taskType: TaskType.SpaAndMassage,
    description: 'Restock minibar in the room.',
    timeCreated: new Date('2024-10-22T13:00:00'),
    assignee: null,
    status: TaskStatus.Pending,
  },
  {
    id: 14,
    roomId: 503,
    taskType: TaskType.RoomCleaning,
    description: 'Quick cleaning requested after checkout.',
    timeCreated: new Date('2024-10-22T09:00:00'),
    assignee: 'Mary S.',
    status: TaskStatus.Completed,
  },
  {
    id: 15,
    roomId: 505,
    taskType: TaskType.Maintenance,
    description: 'AC unit not working properly.',
    timeCreated: new Date('2024-10-22T12:30:00'),
    assignee: null,
    status: TaskStatus.Pending,
  },
  {
    id: 16,
    roomId: 507,
    taskType: TaskType.Maintenance,
    description: 'Request for additional blankets.',
    timeCreated: new Date('2024-10-22T14:00:00'),
    assignee: 'John Doe',
    status: TaskStatus.Completed,
  },
  {
    id: 17,
    roomId: 602,
    taskType: TaskType.RoomCleaning,
    description: 'Scheduled cleaning for the evening.',
    timeCreated: new Date('2024-10-21T18:00:00'),
    assignee: 'Anna P.',
    status: TaskStatus.InProgress,
  },
  {
    id: 18,
    roomId: 604,
    taskType: TaskType.SpaAndMassage,
    description: 'Guest requested a dinner reservation at a nearby restaurant.',
    timeCreated: new Date('2024-10-21T17:00:00'),
    assignee: 'Lisa M.',
    status: TaskStatus.Completed,
  },
  {
    id: 19,
    roomId: 606,
    taskType: TaskType.WakeUpCall,
    description: 'Set wake-up call for 6 AM.',
    timeCreated: new Date('2024-10-22T06:00:00'),
    assignee: null,
    status: TaskStatus.Pending,
  },
  {
    id: 20,
    roomId: 608,
    taskType: TaskType.RoomCleaning,
    description: 'Post-checkout cleaning required.',
    timeCreated: new Date('2024-10-21T16:00:00'),
    assignee: 'Kathy B.',
    status: TaskStatus.InProgress,
  },
  {
    id: 21,
    roomId: 702,
    taskType: TaskType.SpaAndMassage,
    description: 'Restock minibar in the room.',
    timeCreated: new Date('2024-10-22T11:30:00'),
    assignee: null,
    status: TaskStatus.Pending,
  },
  {
    id: 22,
    roomId: 704,
    taskType: TaskType.FoodDelivery,
    description: 'Guest ordered a light breakfast in the room.',
    timeCreated: new Date('2024-10-22T08:00:00'),
    assignee: 'Paul A.',
    status: TaskStatus.Completed,
  },
  {
    id: 23,
    roomId: 706,
    taskType: TaskType.LaundryService,
    description: 'Pick up laundry for express service.',
    timeCreated: new Date('2024-10-22T09:00:00'),
    assignee: 'Nina V.',
    status: TaskStatus.InProgress,
  },
  {
    id: 24,
    roomId: 802,
    taskType: TaskType.RoomCleaning,
    description: 'Deep cleaning requested for long-term guest.',
    timeCreated: new Date('2024-10-22T10:30:00'),
    assignee: 'George R.',
    status: TaskStatus.InProgress,
  },
  {
    id: 25,
    roomId: 804,
    taskType: TaskType.FoodDelivery,
    description: 'Guest requested dinner for two in the room.',
    timeCreated: new Date('2024-10-22T19:00:00'),
    assignee: null,
    status: TaskStatus.Pending,
  },
  {
    id: 26,
    roomId: 805,
    taskType: TaskType.RoomCleaning,
    description: 'Scheduled room cleaning for tomorrow morning.',
    timeCreated: new Date('2024-10-21T07:30:00'),
    assignee: 'Anna P.',
    status: TaskStatus.Pending,
  },
  {
    id: 27,
    roomId: 807,
    taskType: TaskType.Maintenance,
    description: 'Fix the leaking showerhead.',
    timeCreated: new Date('2024-10-22T13:45:00'),
    assignee: null,
    status: TaskStatus.Pending,
  },
  {
    id: 28,
    roomId: 902,
    taskType: TaskType.Maintenance,
    description: 'Request for more towels in the room.',
    timeCreated: new Date('2024-10-22T12:00:00'),
    assignee: 'Jane Smith',
    status: TaskStatus.InProgress,
  },
  {
    id: 29,
    roomId: 904,
    taskType: TaskType.FoodDelivery,
    description: 'Guest ordered room service breakfast.',
    timeCreated: new Date('2024-10-22T07:45:00'),
    assignee: 'Mark T.',
    status: TaskStatus.Completed,
  },
  {
    id: 30,
    roomId: 906,
    taskType: TaskType.RoomCleaning,
    description: 'Regular room cleaning scheduled for tomorrow.',
    timeCreated: new Date('2024-10-22T16:00:00'),
    assignee: 'Sarah Lee',
    status: TaskStatus.InProgress,
  },
  {
    id: 31,
    roomId: 908,
    taskType: TaskType.Maintenance,
    description: 'Fix the air conditioning unit in the room.',
    timeCreated: new Date('2024-10-21T10:00:00'),
    assignee: null,
    status: TaskStatus.Pending,
  },
  {
    id: 32,
    roomId: 1002,
    taskType: TaskType.FoodDelivery,
    description: 'Guest requested a late-night snack.',
    timeCreated: new Date('2024-10-21T23:00:00'),
    assignee: 'John Doe',
    status: TaskStatus.Completed,
  },
  {
    id: 33,
    roomId: 1004,
    taskType: TaskType.RoomCleaning,
    description: 'General cleaning before new guest arrives.',
    timeCreated: new Date('2024-10-22T11:00:00'),
    assignee: 'Mary S.',
    status: TaskStatus.InProgress,
  },
  {
    id: 34,
    roomId: 1006,
    taskType: TaskType.FoodDelivery,
    description: 'Room service dinner for the guest at 8 PM.',
    timeCreated: new Date('2024-10-22T20:00:00'),
    assignee: null,
    status: TaskStatus.Pending,
  },
  {
    id: 35,
    roomId: 1008,
    taskType: TaskType.RoomCleaning,
    description: 'Post-checkout cleaning required for the room.',
    timeCreated: new Date('2024-10-22T13:00:00'),
    assignee: 'Paul A.',
    status: TaskStatus.InProgress,
  },
];
