services:
  accounts_mongo:
    image: mongo:4.4.18
    container_name: accounts_mongo
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  accounts:
    image: conciergeapp/concierge:accounts
    build: .
    ports:
      - 50001:8080
    depends_on:
      - accounts_mongo
    environment:
      - SESSIONS_ENDPOINT=http://permissions:8080
    env_file: 
      - .env.prod
volumes:
  mongo_data:
    driver: local