services:
  accounts:
    build: .
    env_file:
      - .env.dev
    ports:
      - 50001:8080


  accounts-mongo:
    image: mongo:4.4.18
    container_name: accounts-mongo-container
    ports:
      - "27017:27017"
    env_file:
      - .env.dev

