name: Run Integration Tests
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
    
jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build the Docker image
        run: docker compose -f ./docker-compose/docker-compose.yaml up --build --wait --wait-timeout 300 -d

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '/home/runner/work/Concierge/Concierge/src/guest_webapp/'

      - name: Node dependencies
        run: npm install /home/runner/work/Concierge/Concierge/src/guest_webapp/package-lock.json
        
      - name: Run Cypress integration test
        uses: cypress-io/github-action@v6
        with: 
          run-tests: '/home/runner/work/Concierge/Concierge/src/guest_webapp/cypress/e2e/*.cy.js'


