name: Run Integration Tests
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
    
jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build the Docker image
        run: docker compose -f ./docker-compose/docker-compose.yaml build --wait --wait-timeout 300
        
      - name: set directory
        run: cd /home/runner/work/Concierge/Concierge/src/guest_webapp/

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          cache: 'npm'

      - name: Node dependencies
        run: npm install
        
      - name: Run Cypress integration test
        uses: cypress-io/github-action@v6


