name: Run Integration Tests
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
    
jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build the Docker image
        run: docker compose -f ./docker-compose/docker-compose.yaml up --build --wait --wait-timeout 300 -d

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '/home/runner/work/Concierge/Concierge/src/guest_webapp/'

      - name: Node dependencies
        run: npm install /home/runner/work/Concierge/Concierge/src/guest_webapp/
        
      - name: Run Cypress integration test
        uses: cypress-io/github-action@v6
        with: 
          headless: true
          config-file: '/home/runner/work/Concierge/Concierge/src/guest_webapp/cypress.config.js'
          run-tests: '/home/runner/work/Concierge/Concierge/src/guest_webapp/cypress/e2e/*.cy.js'
          working-directory: /home/runner/work/Concierge/Concierge/src/guest_webapp/


      - strategy:
          fail-fast: false
          matrix:
            python-version: ["3.9", "3.10", "3.11"]
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            cd /home/runner/work/Concierge/Concierge/src/accounts/
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
       

      - name: Accounts integration tests
        run: |
          cd /home/runner/work/Concierge/Concierge/src/accounts/
          python3 -m integration_tests