name: Run Integration Tests
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
    
jobs:
  cypress_e2e_integration_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build the Docker image
        run: docker compose -f ./docker-compose/docker-compose.yaml up --build --wait --wait-timeout 300 -d

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '/home/runner/work/Concierge/Concierge/src/guest_webapp/'

      - name: Node dependencies
        run: npm install /home/runner/work/Concierge/Concierge/src/guest_webapp/
        
      - name: Run Cypress integration tests
        uses: cypress-io/github-action@v6
        with: 
          headed: false
          config-file: '/home/runner/work/Concierge/Concierge/src/guest_webapp/cypress.config.js'
          working-directory: /home/runner/work/Concierge/Concierge/src/guest_webapp/

        name: Node dependencies
        run: npm install /home/runner/work/Concierge/Concierge/src/staff_webapp/
        
      - name: Run Cypress integration tests
        uses: cypress-io/github-action@v6
        with: 
          headed: false
          config-file: '/home/runner/work/Concierge/Concierge/src/staff_webapp/cypress.config.js'
          working-directory: /home/runner/work/Concierge/Concierge/src/staff_webapp/

        name: Node dependencies
        run: npm install /home/runner/work/Concierge/Concierge/src/staff_webapp/
        
      - name: Run Cypress e2e tests
        uses: cypress-io/github-action@v6
        with: 
          headed: false
          config-file: '/home/runner/work/Concierge/Concierge/src/system_tests/cypress.config.js'
          working-directory: /home/runner/work/Concierge/Concierge/src/system_tests/