name: Run unit tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  account_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Runs the tests for the account service
    - run: cd ./src/accounts/ 
    - run: pip install -r requirements.txt
    - run: python3 -m tests
