
name: Semgrep CI

#References:
#https://semgrep.dev/docs/semgrep-ci/sample-ci-configs#github-actions



on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install python semgrep package
      run: |
        python -m pip install --upgrade pip
        pip install semgrep

    - name: Run semgrep and publish as json
      run: |
        semgrep --config=auto --output=semgrep-results.json --json .
        
    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: semgrep-results
        path: semgrep-results.json
