name: Task System PostgreSQL Integration Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/task_system/task_system_integration_test/task_system_integration_test.csproj

      - name: Build project
        run: dotnet build ./src/task_system/task_system_integration_test/task_system_integration_test.csproj --configuration Release

      - name: Build and Run Docker Compose
        run: docker compose -f ./src/task_system/docker-compose.test.yaml up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            if docker exec task_system_postgres_test pg_isready -U postgres; then
              echo "PostgreSQL is ready"
              break
            else
              echo "Waiting for PostgreSQL..."
              sleep 5
            fi
          done

      - name: Run Task System Integration Tests
        env:
          CONNECTION_STRING: "Host=127.0.0.1;Port=50021;Username=postgres;Password=sa;Database=task_system_db_integration_test"
        run: dotnet test ./src/task_system/task_system_integration_test/task_system_integration_test.csproj --configuration Release --verbosity normal

      - name: Tear Down Docker Compose
        if: always()
        run: docker compose -f ./src/task_system/docker-compose.test.yaml down